{
 "title": "Application",
 "tags": [ "application" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stratadesk_requests_total[1m])) by (method, route, status)",
     "legendFormat": "{{method}} {{route}} ({{status}})"
    }
   ]
  },
  {
   "title": "Mean Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(stratadesk_request_duration_ms_sum[1m]) / rate(stratadesk_request_duration_ms_count[1m])",
     "legendFormat": "Mean Latency"
    }
   ]
  },
  {
   "title": "Active Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "stratadesk_active_requests", "legendFormat": "Active Requests" }
   ]
  },
  {
   "title": "Error Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(stratadesk_request_errors_total[1m])",
     "legendFormat": "Errors rate"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "stratadesk_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Node.js Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "stratadesk_memory_usage_bytes", "legendFormat": "{{type}}" }
   ]
  }
 ]
}