{
 "title": "Database",
 "tags": [ "database" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{datname=\"stratadesk\"})",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Transaction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=\"stratadesk\"}[1m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=\"stratadesk\"}[1m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Database Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit{datname=\"stratadesk\"}[1m])) / (sum(rate(pg_stat_database_blks_hit{datname=\"stratadesk\"}[1m])) + sum(rate(pg_stat_database_blks_read{datname=\"stratadesk\"}[1m]))) * 100",
     "legendFormat": "Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Database Conflicts & Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_conflicts{datname=\"stratadesk\"})",
     "legendFormat": "Conflicts"
    },
    { "expr": "sum(pg_locks_count)", "legendFormat": "Locks Count" }
   ]
  },
  {
   "title": "Slow Query Metrics / Statements Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls[1m])) by (query)",
     "legendFormat": "Query: {{query}}"
    },
    {
     "expr": "sum(pg_stat_activity_max_tx_duration{datname=\"stratadesk\"})",
     "legendFormat": "Max Transaction Duration (s)"
    }
   ]
  }
 ]
}